### ISSUE TITLE
Module incompatibility with css of content links

### ISSUE THREAD

**Issue by kristianserrano** [krbz999/visual-active-effects#56]
The black color of content links against the dark background in the effect descriptions makes the links difficult to read. I think using the `navajowhite` that's used in the heading for the color of the links works well.

**Comment by krbz999** [comment]
![image](https://github.com/krbz999/visual-active-effects/assets/50169243/e97ca62f-b320-4528-a45a-0309e8816834)

I am not seeing what you are seeing.

**Comment by kristianserrano** [comment]
This is what I'm seeing.

![Screenshot 2024-01-20 at 4 36 07 PM](https://github.com/krbz999/visual-active-effects/assets/1796189/bc9d796e-063b-4d8d-8c31-7f6f75a5478a)

And this is the CSS being applied.

```css
section.visual-active-effects .effect-item .effect-info .effect-info-details .inline-roll, section.visual-active-effects .effect-item .effect-info .effect-info-details .content-link {
    color: black;
}
```
