### ISSUE TITLE
VAE overlaps sidebar if camera dock is set to right

### ISSUE THREAD

**Issue by mhilbrunner** [krbz999/visual-active-effects#83]
The VAE UI overlaps the sidebar/chat if the Foundry camera dock is set to right.

This may be fixed by https://github.com/krbz999/visual-active-effects/issues/74.

Until then, this custom CSS appears to work as a workaround for me:
```css
body:has(.camera-position-right) {
	#visual-active-effects {
		margin-right: 17.5em;
	}
}
body:has(.camera-position-top) {
	#visual-active-effects {
		margin-top: 14em;
	}
}
```
